services:
  nautilus-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.0
    container_name: nautilus-api
    working_dir: /go/src/github.com/tamaco489/async_serverless_application_demo/api/nautilus
    volumes:
      - ./nautilus:/go/src/github.com/tamaco489/async_serverless_application_demo/api/nautilus
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8080:8080"

  coral-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.0
    container_name: coral-api
    working_dir: /go/src/github.com/tamaco489/async_serverless_application_demo/api/coral
    volumes:
      - ./coral:/go/src/github.com/tamaco489/async_serverless_application_demo/api/coral
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8082:8080"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000

  localstack:
    image: localstack/localstack:latest
    container_name: nautilus-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 1
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /var/lib/localstack
    volumes:
      - "./ibis/scripts/localstack/s3_init.sh:/etc/localstack/init/ready.d/s3_init.sh"
    entrypoint: >
      /bin/bash -c "awslocal configure set cli_follow_urlparam false && docker-entrypoint.sh"
